### ISSUE TITLE
bug: "crypto.randomUUID" error breaks page load when inspector is installed as a plugin (v2026.1.1-.3)

### ISSUE THREAD

**Issue by ath0mas** [appium/appium-inspector#2603]
### Is this an issue specifically with Appium Inspector?

- [x] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Run `appium plugin install inspector` to install the current version, **v2026.1.3**,
then launch the Appium server with the plugin activated, with `appium --use-plugins=inspector`.

Everything starts fine, http://myserver:4723/status is ok,
but opening the http://myserver:4723/inspector page fails.

The browser DevTools console shows an error:
> Uncaught TypeError: crypto.randomUUID is not a function

### Expected Behavior

Opening the http://myserver:4723/inspector page should give access to the Inspector.

Confirmed to work as expected forcing the version to **2025.11.1** for example, `appium plugin install inspector@2025.11.1`.

### Operating System

Linux

### Appium Inspector Version

2026.1.1 - 2026.1.3

### Appium Version

3.1.1

### Further Information

Error located in [reducers/SessionBuilder.js#L66](https://github.com/eglitise/appium-inspector/blob/main/app/common/renderer/reducers/SessionBuilder.js#L66), but probably not the only place.

Caused by https://github.com/appium/appium-inspector/pull/2457

**Comment by ath0mas** [comment]
For my Appium server setup, I'm using the [appium/appium](https://hub.docker.com/r/appium/appium/) docker image, with tag `v3.1.1-p0`.
About my browsers, I'm using Chrome 144 and Firefox 147-149.

To debug this, I just installed `appium` locally:
- `npm i -g appium` : v3.2.0
- `appium plugin install inspector@2026.1.2` (to match yours)
- `appium --use-plugins=inspector`

✅ working in all of my browsers:
- `crypto.randomUUID` is a function, and not undefined
- http://127.0.0.1:4723/inspector

❌ failing:
- http://my-local-ip-or-name:4723/inspector

---

OK. Found it! 😃 
https://developer.mozilla.org/en-US/docs/Web/API/Crypto, and look for `Secure context`
**Crypto: randomUUID() method**
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility).

And indeed, access to my Appium server goes through HTTP and not HTTPS, so `isSecureContext` is `false` and `crypto.randomUUID` is unavailable.
